import {
    t,
    type TranslationKey,
} from './i18n';
import { getLocale } from './locale';

const statusKeys:
    Record<number, TranslationKey> = {
        401: 'errors.session',
        419: 'errors.session',
        403: 'errors.forbidden',
        404: 'errors.notFound',
        409: 'errors.conflict',
        413: 'errors.file',
        422: 'errors.validation',
        429: 'errors.throttled',
        500: 'errors.server',
        501: 'errors.server',
        502: 'errors.server',
        503: 'errors.server',
        504: 'errors.server',
    };

const trustedServerValidationCodes =
    new Set([
        'password_reuse',
        'permanent_delete_requires_archive',
        'permanent_delete_blocked',
    ]);

const safeBusinessMessages: Record<
    string,
    { ar: string; en: string }
> = {
    BILLING_UNAVAILABLE: {
        ar: 'تعذر بدء الدفع حاليًا. تحقق من إعداد الاشتراك ثم حاول مرة أخرى.',
        en: 'Checkout could not be started right now. Check the subscription setup and try again.',
    },
    BILLING_PORTAL_UNAVAILABLE: {
        ar: 'تعذر فتح إدارة الاشتراك حاليًا. حاول مرة أخرى بعد قليل.',
        en: 'Subscription management could not be opened right now. Please try again shortly.',
    },
    SUBSCRIPTION_ALREADY_EXISTS: {
        ar: 'لديك اشتراك موجود بالفعل. استخدم إدارة الاشتراك بدل إنشاء اشتراك جديد.',
        en: 'This workspace already has a subscription. Manage it instead of starting another one.',
    },
};

/**
 * Normalize transport failures into translated, user-safe feedback.
 *
 * Raw server text is rejected unless it is paired with an explicitly trusted
 * stable business-validation code generated by AccoNova itself.
 */
export function normalizeApiError(
    error: unknown,
): {
    generalMessage: string;

    fieldErrors:
        Record<string, string[]>;
} {
    const input =
        error &&
        typeof error ===
            'object'
            ? (
                  error as Record<
                      string,
                      unknown
                  >
              )
            : {};

    const status =
        typeof input.status ===
        'number'
            ? input.status
            : 0;

    const fieldErrors:
        Record<string, string[]> =
            {};

    const errors =
        input.errors &&
        typeof input.errors ===
            'object'
            ? (
                  input.errors as Record<
                      string,
                      unknown
                  >
              )
            : {};

    const codes =
        input.error_codes &&
        typeof input.error_codes ===
            'object'
            ? (
                  input.error_codes as Record<
                      string,
                      string[]
                  >
              )
            : {};

    if (
        status ===
        422
    ) {
        for (
            const field of Object.keys(
                errors,
            )
        ) {
            const rules =
                Array.isArray(
                    codes[
                        field
                    ],
                )
                    ? codes[
                          field
                      ]
                    : [];

            const rawMessages =
                Array.isArray(
                    errors[
                        field
                    ],
                )
                    ? errors[
                          field
                      ].filter(
                          (
                              message,
                          ): message is string =>
                              typeof message ===
                              'string',
                      )
                    : [];

            const trustedBusinessValidation =
                rules.some(
                    (
                        code,
                    ) =>
                        trustedServerValidationCodes.has(
                            code,
                        ),
                );

            if (
                trustedBusinessValidation &&
                rawMessages[0]
            ) {
                fieldErrors[
                    field
                ] = [
                    rawMessages[
                        0
                    ],
                ];

                continue;
            }

            const key:
                TranslationKey =
                rules.includes(
                    'unique',
                )
                    ? field ===
                      'sku'
                        ? 'errors.sku'
                        : field ===
                            'email'
                          ? 'errors.emailUsed'
                          : 'errors.unique'
                    : rules.includes(
                            'required',
                        )
                      ? 'errors.required'
                      : rules.includes(
                              'email',
                          )
                        ? 'errors.email'
                        : field ===
                            'file'
                          ? 'errors.file'
                          : 'errors.invalidField';

            fieldErrors[
                field
            ] = [
                t(
                    key,
                ),
            ];
        }
    }

    const errorId =
        typeof input.error_id ===
        'string'
            ? input.error_id
            : '';

    const code =
        typeof input.code === 'string'
            ? input.code
            : '';

    const safeBusinessMessage =
        safeBusinessMessages[code];

    const baseMessage = safeBusinessMessage
        ? safeBusinessMessage[getLocale()]
        : t(
              statusKeys[
                  status
              ] ??
                  (
                      status ===
                      0
                          ? 'errors.network'
                          : 'errors.unexpected'
                  ),
          );

    return {
        generalMessage:
            errorId
                ? baseMessage
                    + ' #'
                    + errorId
                : baseMessage,

        fieldErrors,
    };
}
