import { ConfirmDialog } from '@/components/feedback/ConfirmDialog';
import { AppShell } from '@/layouts/AppShell';
import { ApiError, apiRequest } from '@/lib/http';
import { useLocale } from '@/lib/i18n';
import { staffCopy } from '@/lib/staffCopy';
import type { AppPageProps } from '@/types/app';
import { Head, Link, usePage } from '@inertiajs/react';
import { ShieldCheck, Plus, Check, Users, Boxes, Wallet, ContactRound, Package, Pencil } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
type Role={id:number;name:string;base_role:string;permissions:string[];is_custom:boolean};
type Member={id:number;user_id:number;role:string;workspace_role_id:number|null;user:{name:string;email:string}};
const groups=[{key:'products',icon:Package,actions:['view','create','update','service','archive']},{key:'parties',icon:ContactRound,actions:['view','create','update','archive']},{key:'inventory',icon:Boxes,actions:['view','manage']},{key:'payments',icon:Wallet,actions:['view','create','update','recordPayment']},{key:'staff',icon:Users,actions:['view','manage','pay','team_view','team_pay']}] as const;
const field='mt-2 w-full rounded-xl border border-[var(--ac-line)] bg-[var(--ac-surface-soft)] p-3 text-sm';
const button='rounded-xl border border-[var(--ac-line)] bg-white px-4 py-3 text-sm transition hover:bg-[var(--ac-accent-soft)] disabled:opacity-50';
export default function Roles(){const {workspace}=usePage<AppPageProps>().props;return <RoleWorkspace key={workspace.activeOrganization?.id}/>;}
function RoleWorkspace(){
 const c=staffCopy[useLocale()];const {workspace}=usePage<AppPageProps>().props;const allowed=workspace.activeOrganization?.role==='owner';const [data,setData]=useState<{roles:Role[];members:Member[]}|null>(null);const [revision,setRevision]=useState(0);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [editing,setEditing]=useState<Role|null>(null);const [name,setName]=useState('');const [permissions,setPermissions]=useState<string[]>([]);const [success,setSuccess]=useState(false);const [preview,setPreview]=useState<{id:number;name:string;email:string}|null>(null);const [revoking,setRevoking]=useState<Member|null>(null);
 useEffect(()=>{if(!allowed)return;const ctrl=new AbortController();apiRequest<NonNullable<typeof data>>('/api/workspace-roles',{signal:ctrl.signal}).then(setData).catch((e:unknown)=>{if(!ctrl.signal.aborted)setError(e instanceof ApiError?e.message:c.failed);});return()=>ctrl.abort();},[allowed,revision,c.failed]);
 async function send(path:string,body:unknown,method='POST'){if(busy)return false;setBusy(true);setError('');setSuccess(false);try{await apiRequest(path,{method,body:JSON.stringify(body)});setRevision(v=>v+1);setSuccess(true);return true;}catch(e){setError(e instanceof ApiError?[e.message,...Object.values(e.errors).flat()].join(' '):c.failed);return false;}finally{setBusy(false);}}
 async function save(e:FormEvent){e.preventDefault();if(await send(editing?'/api/workspace-roles/'+editing.id:'/api/workspace-roles',{name,permissions,is_custom:true,base_role:'employee'},editing?'PATCH':'POST')){setEditing(null);setName('');setPermissions([]);}}
 async function assign(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));if(!preview){setBusy(true);setError('');try{setPreview(await apiRequest('/api/workspace-roles/preview',{method:'POST',body:JSON.stringify({email:values.email})}));}catch(e){setError(e instanceof ApiError?e.message:c.failed);}finally{setBusy(false);}return;}if(await send('/api/workspace-roles/assign',{...values,confirmed_user_id:preview.id})){form.reset();setPreview(null);}}
 function toggle(permission:string){setPermissions(current=>{const [module,action]=permission.split('.');if(current.includes(permission))return current.filter(item=>item!==permission&&(action!=='view'||!item.startsWith(module+'.')));const dependencies=module==='inventory'?['products.view']:permission==='products.service'?['parties.view']:[]; const view=action.startsWith('team_')?'staff.team_view':module+'.view'; return [...new Set([...current,permission,view,...dependencies])];});}
 return <AppShell><Head title={c.roles}/><main className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-8"><header className="flex flex-wrap items-center justify-between gap-5 rounded-[28px] border border-[var(--ac-line)] bg-gradient-to-br from-white to-[var(--ac-accent-soft)] p-8"><div className="flex items-start gap-4"><span className="rounded-2xl bg-[var(--ac-accent-soft)] p-4"><ShieldCheck size={28}/></span><div><h1 className="text-3xl font-semibold">{c.roles}</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-[var(--ac-text-soft)]">{c.customHelp}</p></div></div><Link href="/app/departments" className={button}>{c.departments}</Link></header>{!allowed?<p>{c.ownerOnly}</p>:<>{error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}{success&&<p role="status" className="flex items-center gap-2 text-sm text-emerald-700"><Check size={16}/>{c.success}</p>}
 <div className="grid items-start gap-6 lg:grid-cols-[1fr_320px]"><form onSubmit={e=>void save(e)} className="rounded-[24px] border border-[var(--ac-line)] bg-white p-5 sm:p-7"><fieldset disabled={busy}><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">{editing?c.editRole:c.newRole}</h2><span className="rounded-full bg-[var(--ac-accent-soft)] px-3 py-1 text-xs">{permissions.length} ? {c.permissions}</span></div><label className="mt-5 block text-xs">{c.roleName}<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} className={field}/></label><div className="mt-5 flex flex-wrap gap-2"><button type="button" className={button} onClick={()=>{setName(c.salesPreset);setPermissions(['products.view','products.service','parties.view','parties.create','parties.update']);}}>{c.salesPreset}</button><button type="button" className={button} onClick={()=>{setName(c.managerPreset);setPermissions(['staff.team_view']);}}>{c.managerPreset}</button></div><p className="mt-3 text-xs leading-6 text-[var(--ac-text-muted)]">{c.presetHelp}</p><div className="mt-6 space-y-3">{groups.map(group=>{const Icon=group.icon;return <section key={group.key} className="rounded-2xl border border-[var(--ac-line)] p-4"><h3 className="mb-3 flex items-center gap-2 text-sm font-semibold"><Icon size={17}/>{c[group.key]}</h3><div className="flex flex-wrap gap-2">{group.actions.map(action=>{const key=group.key+'.'+(action==='recordPayment'?'record':action);const checked=permissions.includes(key);return <button key={action} type="button" aria-pressed={checked} onClick={()=>toggle(key)} className={'flex items-center gap-2 rounded-xl border px-4 py-2.5 text-xs transition '+(checked?'border-[var(--ac-accent)] bg-[var(--ac-accent-soft)] font-semibold text-[var(--ac-accent-strong)]':'border-[var(--ac-line)] text-[var(--ac-text-soft)] hover:bg-[var(--ac-surface-soft)]')}><span className={'flex size-4 items-center justify-center rounded border '+(checked?'border-[var(--ac-accent)] bg-[var(--ac-accent-strong)] text-white':'border-[var(--ac-line)]')}>{checked&&<Check size={12}/>}</span>{c[action]}</button>;})}</div></section>;})}</div><div className="mt-6 flex gap-3"><button className="rounded-xl bg-[var(--ac-accent-strong)] px-7 py-3 text-sm font-semibold text-white">{c.save}</button>{editing&&<button type="button" className={button} onClick={()=>{setEditing(null);setName('');setPermissions([]);}}>{c.cancel}</button>}</div></fieldset></form>
 <aside className="space-y-5"><section className="rounded-[24px] border border-[var(--ac-line)] bg-white p-5"><h2 className="mb-4 font-semibold">{c.roleLibrary}</h2><div className="space-y-3">{data?.roles.map(role=><button key={role.id} disabled={busy} onClick={()=>{setEditing(role);setName(role.name);setPermissions(role.permissions.flatMap(p=>p==='products.manage'?['products.view','products.create','products.update','products.service']:p==='parties.manage'?['parties.view','parties.create','parties.update']:p==='payments.manage'?['payments.view','payments.create','payments.update','payments.record']:[p]));}} className={'w-full rounded-2xl border p-4 text-start transition '+(editing?.id===role.id?'border-[var(--ac-accent)] bg-[var(--ac-accent-soft)]':'border-[var(--ac-line)] hover:bg-[var(--ac-surface-soft)]')}><div className="flex justify-between gap-2"><strong className="text-sm">{role.name}</strong><Pencil size={14}/></div><p className="mt-2 text-xs text-[var(--ac-text-muted)]">{role.permissions.length} ? {c.permissions}</p>{!role.is_custom&&<p className="mt-2 text-xs text-amber-700">{c.legacy}</p>}</button>)}</div></section><form onChange={()=>setPreview(null)} onSubmit={e=>void assign(e)} className="rounded-[24px] border border-[var(--ac-line)] bg-white p-5"><h2 className="mb-4 font-semibold">{c.assign}</h2><fieldset disabled={busy||!data?.roles.length} className="space-y-4"><label className="block text-xs">{c.email}<input required name="email" type="email" className={field}/></label><fieldset><legend className="text-xs">{c.selectRole}</legend><div className="mt-2 space-y-2">{data?.roles.map(role=><label key={role.id} className="flex items-center gap-2 rounded-xl bg-[var(--ac-surface-soft)] p-3 text-sm"><input required type="radio" name="workspace_role_id" value={role.id}/>{role.name}</label>)}</div></fieldset><div aria-live="polite">{preview&&<div className="rounded-xl bg-[var(--ac-accent-soft)] p-4 text-sm"><strong>{preview.name}</strong><bdi className="mt-2 block break-all">{preview.email}</bdi></div>}</div><button className="w-full rounded-xl bg-[var(--ac-accent-strong)] p-3 text-sm text-white">{preview?c.confirmAssignment:c.previewUser}</button></fieldset></form></aside></div>
 <section className="rounded-[24px] border border-[var(--ac-line)] bg-white p-6"><h2 className="mb-5 flex items-center gap-2 font-semibold"><Users size={19}/>{c.members}</h2><div className="grid gap-3 md:grid-cols-2">{data?.members.map(member=><article key={member.id} className="flex items-center gap-3 rounded-2xl bg-[var(--ac-surface-soft)] p-4"><span className="flex size-10 shrink-0 items-center justify-center rounded-full bg-white font-semibold">{member.user.name.charAt(0)}</span><div className="min-w-0"><strong className="block truncate text-sm">{member.user.name}</strong><p className="mt-1 truncate text-xs text-[var(--ac-text-muted)]">{member.user.email}</p></div><span className="ms-auto rounded-full bg-white px-3 py-1 text-xs">{data.roles.find(r=>r.id===member.workspace_role_id)?.name??member.role}</span>{member.role!=='owner'&&<button disabled={busy} type="button" className="rounded-lg border border-red-200 px-2 py-2 text-xs text-red-700" onClick={()=>setRevoking(member)}>{c.revokeAccess}</button>}</article>)}</div></section></>}</main><ConfirmDialog open={!!revoking} title={c.revokeAccess} description={(revoking?.user.name??'')+' ? '+(revoking?.user.email??'')+' ? '+c.revokeHelp} confirmLabel={c.revokeAccess} tone="danger" busy={busy} onCancel={()=>setRevoking(null)} onConfirm={async()=>{if(revoking&&await send('/api/organizations/'+workspace.activeOrganization?.id+'/memberships/'+revoking.id,{},'DELETE'))setRevoking(null);}}/></AppShell>;
}
