import { ApiError, apiRequest } from '@/lib/http';
import { useLocale } from '@/lib/i18n';
import { staffCopy } from '@/lib/staffCopy';
import type { AppPageProps } from '@/types/app';
import { Head, Link, usePage } from '@inertiajs/react';
import { ShieldCheck } from 'lucide-react';
import { useState, type FormEvent } from 'react';
export default function StaffInvitation(){
 const c=staffCopy[useLocale()];const {auth,invitation}=usePage<AppPageProps & {invitation:{name:string;email:string;organization:string;token:string}}>().props;
 const [register,setRegister]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const values=Object.fromEntries(new FormData(e.currentTarget));try{if(auth.user){const response=await apiRequest<{url:string}>('/api/staff-invitations/'+invitation.token+'/accept',{method:'POST'});window.location.assign(response.url);}else{await apiRequest(register?'/api/register':'/api/login',{method:'POST',body:JSON.stringify({...values,email:invitation.email})});window.location.reload();}}catch(failure){setError(failure instanceof ApiError?[failure.message,...Object.values(failure.errors).flat()].join(' '):c.failed);}finally{setBusy(false);}}
 const field='mt-2 w-full rounded-xl border border-[var(--ac-line)] bg-[var(--ac-surface-soft)] p-3 text-sm';
 const matches=auth.user?.email.toLowerCase()===invitation.email.toLowerCase();
 return <><Head title={c.join}/><main className="flex min-h-screen items-center justify-center bg-[var(--ac-bg)] px-4 py-10"><section className="w-full max-w-lg rounded-[28px] border border-[var(--ac-line)] bg-[var(--ac-surface)] p-7 shadow-sm sm:p-10"><ShieldCheck size={40} className="mb-6 text-[var(--ac-accent-strong)]"/><p className="text-sm text-[var(--ac-text-muted)]">{invitation.organization}</p><h1 className="mt-2 text-2xl font-semibold">{c.join} — {invitation.name}</h1><p className="mt-3 break-all text-sm"><bdi>{invitation.email}</bdi></p><p className="mt-3 text-xs leading-6 text-[var(--ac-text-muted)]">{c.expires}</p>{error&&<p role="alert" className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}
 {auth.user&&!matches?<div className="mt-6"><p className="text-sm">{c.wrongEmail}</p><button className="mt-4 rounded-xl border p-3 text-sm" onClick={async()=>{if(busy)return;setBusy(true);try{await apiRequest('/api/logout',{method:'POST'});window.location.reload();}catch{setError(c.failed);setBusy(false);}}}>{c.login}</button></div>:auth.user&&!auth.user.emailVerified?<div className="mt-6 space-y-4"><Link href="/verify-email" className="block rounded-xl bg-[var(--ac-accent-solid)] p-3 text-center text-sm text-[var(--ac-accent-solid-text)]">{c.verify}</Link><p className="text-xs leading-6">{c.returnLink}</p></div>:<form onSubmit={e=>void submit(e)} className="mt-6"><fieldset disabled={busy} className="space-y-4">{!auth.user&&<><div className="flex gap-2">{[false,true].map(value=><button key={String(value)} type="button" aria-pressed={register===value} onClick={()=>setRegister(value)} className={'flex-1 rounded-xl p-3 text-sm '+(register===value?'bg-[var(--ac-accent-soft)] font-semibold':'bg-[var(--ac-surface-soft)]')}>{value?c.newAccount:c.already}</button>)}</div>{register&&<label className="block text-xs">{c.name}<input required name="name" maxLength={255} defaultValue={invitation.name} autoComplete="name" className={field}/></label>}<label className="block text-xs">{c.password}<input required type="password" name="password" minLength={register?12:undefined} autoComplete={register?'new-password':'current-password'} className={field}/></label>{register&&<label className="block text-xs">{c.confirmPassword}<input required type="password" name="password_confirmation" minLength={12} autoComplete="new-password" className={field}/></label>}</>}<button className="w-full rounded-xl bg-[var(--ac-accent-solid)] p-3 text-sm font-semibold text-[var(--ac-accent-solid-text)]">{auth.user?c.accept:register?c.register:c.login}</button></fieldset></form>}</section></main></>;
}
