<?php

namespace Tests\Feature\Auth;

use App\Models\User;
use Illuminate\Auth\Events\PasswordReset;
use Illuminate\Auth\Notifications\ResetPassword;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Notification;
use Tests\TestCase;

class PasswordRecoveryTest extends TestCase
{
    use RefreshDatabase;

    /**
     * Verify a known account receives Laravel's password reset notification.
     */
    public function test_user_can_request_password_reset_link(): void
    {
        Notification::fake();

        $user = User::factory()->create();

        $this->postJson(
            '/api/forgot-password',
            [
                'email' => strtoupper(
                    $user->email,
                ),
            ],
        )->assertOk();

        Notification::assertSentTo(
            $user,
            ResetPassword::class,
        );
    }

    /**
     * Return an explicit validation error when the submitted recovery email
     * does not belong to an AccoNova account.
     */
    public function test_unknown_email_is_rejected(): void
    {
        Notification::fake();

        $this->postJson(
            '/api/forgot-password',
            [
                'email' => 'unknown@example.com',
            ],
        )
            ->assertUnprocessable()
            ->assertJsonValidationErrors([
                'email',
            ])
            ->assertJsonPath(
                'errors.email.0',
                'No AccoNova account was found with this email address.',
            );

        Notification::assertNothingSent();
    }

    /**
     * Verify a valid broker token replaces the password and emits Laravel's
     * standard PasswordReset event.
     */
    public function test_password_can_be_reset_with_valid_token(): void
    {
        Notification::fake();

        $user = User::factory()->create([
            'password' => 'CurrentPassword123!',
        ]);

        $this->postJson(
            '/api/forgot-password',
            [
                'email' => $user->email,
            ],
        )->assertOk();

        $token = null;

        Notification::assertSentTo(
            $user,
            ResetPassword::class,
            /**
             * Capture the token generated by Laravel's password broker.
             */
            function (
                ResetPassword $notification,
            ) use (&$token): bool {
                $token =
                    $notification->token;

                return true;
            },
        );

        $this->assertNotNull($token);

        Event::fake([
            PasswordReset::class,
        ]);

        $newPassword =
            'CompletelyNewPassword123!';

        $this->postJson(
            '/api/reset-password',
            [
                'email' => $user->email,
                'token' => $token,
                'password' => $newPassword,
                'password_confirmation' => $newPassword,
            ],
        )->assertOk();

        $this->assertTrue(
            Hash::check(
                $newPassword,
                $user->fresh()->password,
            ),
        );

        Event::assertDispatched(
            PasswordReset::class,
        );
    }

    /**
     * Reject a password reset when the replacement password matches the
     * user's current password.
     */
    public function test_password_reset_rejects_current_password(): void
    {
        Notification::fake();

        $currentPassword =
            'CurrentPassword123!';

        $user = User::factory()->create([
            'password' => $currentPassword,
        ]);

        $this->postJson(
            '/api/forgot-password',
            [
                'email' => $user->email,
            ],
        )->assertOk();

        $token = null;

        Notification::assertSentTo(
            $user,
            ResetPassword::class,
            /**
             * Capture Laravel's broker token for the same-password scenario.
             */
            function (
                ResetPassword $notification,
            ) use (&$token): bool {
                $token =
                    $notification->token;

                return true;
            },
        );

        $this->assertNotNull($token);

        $this->postJson(
            '/api/reset-password',
            [
                'email' => $user->email,
                'token' => $token,
                'password' => $currentPassword,
                'password_confirmation' => $currentPassword,
            ],
        )
            ->assertUnprocessable()
            ->assertJsonValidationErrors([
                'password',
            ])
            ->assertJsonPath(
                'errors.password.0',
                'Your new password must be different from your current password.',
            );

        $this->assertTrue(
            Hash::check(
                $currentPassword,
                $user->fresh()->password,
            ),
        );
    }

    /**
     * Reject invalid or expired reset credentials.
     */
    public function test_invalid_reset_token_is_rejected(): void
    {
        $user = User::factory()->create();

        $this->postJson(
            '/api/reset-password',
            [
                'email' => $user->email,
                'token' => 'invalid-token',
                'password' => 'NewPassword123!',
                'password_confirmation' => 'NewPassword123!',
            ],
        )
            ->assertUnprocessable()
            ->assertJsonValidationErrors([
                'email',
            ]);
    }

    /**
     * Enforce AccoNova's password-strength requirement during recovery.
     */
    public function test_reset_rejects_weak_password(): void
    {
        $this->postJson(
            '/api/reset-password',
            [
                'email' => 'user@example.com',
                'token' => 'token',
                'password' => 'short',
                'password_confirmation' => 'short',
            ],
        )
            ->assertUnprocessable()
            ->assertJsonValidationErrors([
                'password',
            ]);
    }
}
