<?php
namespace App\Http\Controllers;
use App\Tenancy\TenantContext;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
class WorkspaceConversationController extends Controller {
 public function index(Request $request): JsonResponse {$data=$request->validate(['search'=>['nullable','string','max:100']]);$query=DB::table('workspace_conversations as c')->where('c.organization_id',app(TenantContext::class)->id())->where(function($q)use($request): void {$q->where('c.is_private',false)->orWhereExists(fn($sub)=>$sub->selectRaw('1')->from('workspace_conversation_members as m')->whereColumn('m.conversation_id','c.id')->where('m.user_id',$request->user()->id));});if(!empty($data['search'])){$query->where('c.name','like','%'.$data['search'].'%');}return response()->json(['data'=>$query->orderByDesc('c.updated_at')->paginate(50)]);}
 public function people(Request $request): JsonResponse {$data=$request->validate(['search'=>['nullable','string','max:100']]);$query=DB::table('memberships')->join('users','users.id','=','memberships.user_id')->where('memberships.organization_id',app(TenantContext::class)->id());if(!empty($data['search'])){$query->where('users.name','like','%'.$data['search'].'%');}return response()->json(['data'=>$query->orderBy('users.name')->limit(50)->get(['users.id','users.name'])]);}
 public function store(Request $request): JsonResponse {$data=$request->validate(['name'=>['required','string','max:100'],'description'=>['nullable','string','max:500'],'is_private'=>['required','boolean'],'members'=>['present','array','max:1000'],'members.*'=>['integer','distinct',Rule::exists('memberships','user_id')->where('organization_id',app(TenantContext::class)->id())]]);$id=DB::transaction(function()use($request,$data): int {$id=DB::table('workspace_conversations')->insertGetId(['organization_id'=>app(TenantContext::class)->id(),'created_by'=>$request->user()->id,'name'=>$data['name'],'description'=>$data['description']??null,'is_private'=>$data['is_private'],'created_at'=>now(),'updated_at'=>now()]);foreach(array_unique([...$data['members'],$request->user()->id]) as $user){DB::table('workspace_conversation_members')->insert(['conversation_id'=>$id,'user_id'=>$user]);}return $id;});return response()->json(['id'=>$id],201);}
 private function conversation(Request $request,string $conversation,bool $lock=false): object {$query=DB::table('workspace_conversations')->where('organization_id',app(TenantContext::class)->id())->where('id',$conversation);if($lock){$query->lockForUpdate();}$row=$query->first();abort_unless($row,404);abort_if($row->is_private&&!DB::table('workspace_conversation_members')->where('conversation_id',$row->id)->where('user_id',$request->user()->id)->exists(),404);return $row;}
 public function messages(Request $request,string $conversation): JsonResponse {$row=$this->conversation($request,$conversation);$data=$request->validate(['before'=>['nullable','integer','min:1']]);$query=DB::table('workspace_messages as m')->join('users','users.id','=','m.user_id')->where('m.conversation_id',$row->id);if(!empty($data['before'])){$query->where('m.id','<',$data['before']);}$messages=$query->orderByDesc('m.id')->limit(50)->get(['m.*','users.name'])->map(function($message): object {if($message->deleted_at){$message->body='';}return $message;});return response()->json(['conversation'=>$row,'messages'=>$messages->reverse()->values(),'members'=>DB::table('workspace_conversation_members as cm')->join('users','users.id','=','cm.user_id')->join('memberships as membership',function($join): void {$join->on('membership.user_id','=','cm.user_id')->where('membership.organization_id',app(TenantContext::class)->id());})->where('cm.conversation_id',$row->id)->get(['users.id','users.name']),'can_manage'=>$row->created_by===$request->user()->id]);}
 public function send(Request $request,string $conversation): JsonResponse {$data=$request->validate(['body'=>['required','string','max:10000'],'request_id'=>['required','uuid']]);$id=DB::transaction(function()use($request,$conversation,$data): int {$row=$this->conversation($request,$conversation,true);$old=DB::table('workspace_messages')->where('conversation_id',$row->id)->where('user_id',$request->user()->id)->where('request_id',$data['request_id'])->first();if($old){abort_if($old->body!==$data['body'],409);return $old->id;}$id=DB::table('workspace_messages')->insertGetId([...$data,'conversation_id'=>$row->id,'user_id'=>$request->user()->id,'created_at'=>now(),'updated_at'=>now()]);DB::table('workspace_conversations')->where('id',$row->id)->update(['updated_at'=>now()]);return $id;});return response()->json(['id'=>$id],201);}
 public function members(Request $request,string $conversation): JsonResponse {$data=$request->validate(['members'=>['present','array','max:1000'],'members.*'=>['integer','distinct',Rule::exists('memberships','user_id')->where('organization_id',app(TenantContext::class)->id())]]);DB::transaction(function()use($request,$conversation,$data): void {$row=$this->conversation($request,$conversation,true);abort_unless($row->created_by===$request->user()->id,403);$ids=array_unique([...$data['members'],$row->created_by]);DB::table('workspace_conversation_members')->where('conversation_id',$row->id)->whereNotIn('user_id',$ids)->delete();foreach($ids as $id){DB::table('workspace_conversation_members')->insertOrIgnore(['conversation_id'=>$row->id,'user_id'=>$id]);}});return response()->json(['saved'=>true]);}
 public function updateMessage(Request $request,string $conversation,string $message): JsonResponse {$data=$request->validate(['body'=>[$request->isMethod('DELETE')?'sometimes':'required','string','max:10000']]);DB::transaction(function()use($request,$conversation,$message,$data): void {$row=$this->conversation($request,$conversation,true);$query=DB::table('workspace_messages')->where('conversation_id',$row->id)->where('id',$message)->whereNull('deleted_at');$entry=(clone $query)->first();abort_unless($entry,404);abort_unless($entry->user_id===$request->user()->id || ($request->isMethod('DELETE')&&$row->created_by===$request->user()->id),403);$query->update($request->isMethod('DELETE')?['deleted_at'=>now(),'updated_at'=>now()]:['body'=>$data['body'],'updated_at'=>now()]);});return response()->json(['saved'=>true]);}
}
