import { useState, type FormEvent } from 'react';
import { createPortal } from 'react-dom';
import { X, Pencil, Trash2 } from 'lucide-react';
import { useDialog } from '@/components/feedback/useDialog';
import { apiRequest, ApiError } from '@/lib/http';
import { useLocale } from '@/lib/i18n';

export type CorrectionTarget = {path:string;title:string;description?:string;remove:boolean;fields?:{name:string;label:string;value:string;type?:string;required?:boolean;options?:{value:string;label:string}[]}[]};
export function CorrectionDialog({target,onClose,onSaved}:{target:CorrectionTarget;onClose:()=>void;onSaved:()=>void}){
 const ar=useLocale()==='ar';const [busy,setBusy]=useState(false),[error,setError]=useState('');const ref=useDialog(true,onClose,busy);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget));for(const key of Object.keys(data)){if(data[key]===''&&key!=='reason')delete data[key];}try{await apiRequest(target.path,{method:target.remove?'DELETE':'PATCH',body:JSON.stringify(data)});onSaved();onClose();}catch(e){setError(e instanceof ApiError?[e.message,...Object.values(e.errors).flat()].join(' '):ar?'تعذّر الحفظ':'Could not save');}finally{setBusy(false);}}
 return createPortal(<div className="fixed inset-0 z-[120] flex items-center justify-center bg-black/25 p-4 backdrop-blur-sm"><section ref={ref} role="dialog" aria-modal="true" aria-labelledby="correction-title" className="max-h-[90dvh] w-full max-w-lg overflow-y-auto rounded-[28px] bg-white p-6 shadow-2xl"><header className="mb-5 flex items-center justify-between gap-3"><div className="flex items-center gap-3">{target.remove?<Trash2 size={20}/>:<Pencil size={20}/>}<h2 id="correction-title" className="font-semibold">{target.title}</h2></div><button disabled={busy} aria-label={ar?'إغلاق':'Close'} onClick={onClose}><X size={20}/></button></header><p className="mb-5 text-xs leading-6 text-[var(--ac-text-muted)]">{target.description??(ar?'سيتم تحديث الرصيد وحفظ أثر التصحيح للرجوع إليه.':'The balance will update and a correction record will be retained.')}</p><form onSubmit={submit}><fieldset disabled={busy} className="space-y-4">{!target.remove&&target.fields?.map(field=><label key={field.name} className="block text-xs">{field.label}{field.options?<select name={field.name} defaultValue={field.value} className="mt-2 w-full rounded-xl border border-[var(--ac-line)] p-3">{field.options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select>:<input required={field.required} name={field.name} type={field.type??'text'} step={field.type==='number'?'0.0001':undefined} min={field.type==='number'?'0':undefined} defaultValue={field.value} className="mt-2 w-full rounded-xl border border-[var(--ac-line)] p-3"/>}</label>)}<label className="block text-xs">{ar?'سبب التصحيح':'Reason for correction'}<textarea required name="reason" maxLength={1000} rows={2} className="mt-2 w-full rounded-xl border border-[var(--ac-line)] p-3"/></label>{error&&<p role="alert" className="text-xs text-red-700">{error}</p>}<div className="flex gap-3 pt-2"><button className={`flex-1 rounded-xl p-3 text-sm font-semibold text-white ${target.remove?'bg-red-700':'bg-[var(--ac-accent-strong)]'}`}>{busy?'…':target.remove?(ar?'تأكيد الحذف':'Confirm deletion'):(ar?'حفظ التصحيح':'Save correction')}</button><button type="button" onClick={onClose} className="rounded-xl border border-[var(--ac-line)] px-4 text-sm">{ar?'إلغاء':'Cancel'}</button></div></fieldset></form></section></div>,document.body);
}
