import { apiRequest, ApiError } from '@/lib/http';
import { useLocale } from '@/lib/i18n';
import { useEffect, useState, type FormEvent } from 'react';

type Rule = {id:number;label:string;kind:string;amount:string;starts_on:string;ends_on:string|null};
type Data = {attendance:{data:{id:number;occurred_on:string;status:string;quantity:string;overtime_hours:string}[];last_page:number};adjustments:Rule[]};
const field='mt-2 w-full rounded-xl border border-[var(--ac-line)] bg-[var(--ac-surface-soft)] p-3 text-sm';
const button='rounded-xl border border-[var(--ac-line)] bg-white px-4 py-2.5 text-sm disabled:opacity-50';
const dateInput=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const today=()=>dateInput(new Date());

export function StaffWorkforcePanel({id,basis,unit,currency,canPay,onChanged}:{id:number;basis:string;unit:string|null;currency:string;canPay:boolean;onChanged:()=>void}){
 const ar=useLocale()==='ar';
 const c=ar?{title:'الحضور والإضافي',help:'اليوم = يوم عمل، الساعة = الساعات الفعلية، القطعة = الوحدات المنجزة. الحضور الشهري للتوثيق؛ الراتب يعتمد بشكل مستقل. الغياب لا يخصم تلقائيًا من الراتب الشهري.',present:'حاضر',absent:'غائب',date:'التاريخ',quantity:basis==='piece'?'عدد الوحدات المنجزة':basis==='hour'?'ساعات العمل':'أيام الحضور',ot:'ساعات إضافية',rate:'أجر الساعة الإضافية المتفق عليه',notes:'ملاحظة / سبب',save:'اعتماد وتسجيل الاستحقاق',rules:'البدلات والحوافز والخصومات المستمرة',ruleHelp:'بنود شهرية مستقلة مثل المواصلات والتأمين والمخاطرة. عند تغيير القيمة، أوقف البند القديم وأضف قيمة جديدة بتاريخ سريانها. الاعتماد يسجّل مبلغًا كاملًا عن كل شهر بدأ فيه البند، بدون تناسب أيام وبدون تسجيل دفع.',label:'اسم البند',kind:'النوع',allowance:'بدل / علاوة',bonus:'حافز / مكافأة',deduction:'خصم',amount:'المبلغ الشهري',start:'يبدأ من',end:'ينتهي في (اختياري)',add:'إضافة بند شهري',through:'اعتماد حتى شهر مكتمل',accrue:'اعتماد البنود الشهرية',stop:'إيقاف من نهاية اليوم',empty:'لا توجد سجلات بعد',previous:'السابق',next:'التالي',failed:'تعذّر الحفظ؛ راجع البيانات.',saved:'تم الحفظ',permanent:'مستمر'}:{title:'Attendance & overtime',help:'Days count as one workday, hours as actual hours and pieces as completed units. Monthly attendance is a record only; salary approval is separate. Absence does not automatically deduct monthly salary.',present:'Present',absent:'Absent',date:'Date',quantity:basis==='piece'?'Completed units':basis==='hour'?'Working hours':'Days present',ot:'Overtime hours',rate:'Agreed overtime hourly rate',notes:'Note / reason',save:'Approve attendance & earnings',rules:'Recurring allowances, incentives & deductions',ruleHelp:'Monthly items such as transport, insurance or risk allowance. To change a rate, end the old item and add a new effective date. Approval records the full amount for each started month, without daily proration or a payment.',label:'Item name',kind:'Type',allowance:'Allowance',bonus:'Bonus / incentive',deduction:'Deduction',amount:'Monthly amount',start:'Starts on',end:'Ends on (optional)',add:'Add monthly item',through:'Approve through completed month',accrue:'Approve monthly items',stop:'End after today',empty:'No records yet',previous:'Previous',next:'Next',failed:'Could not save. Check the values.',saved:'Saved',permanent:'Ongoing'};
 const [data,setData]=useState<Data|null>(null),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[status,setStatus]=useState('present'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 useEffect(()=>{const controller=new AbortController();apiRequest<Data>(`/api/staff/${id}/workforce?page=${page}`,{signal:controller.signal}).then(setData).catch((e:unknown)=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:c.failed);});return()=>controller.abort();},[id,page,revision,c.failed]);
 async function send(path:string,values:Record<string,unknown>,method='POST'){if(busy)return false;setBusy(true);setError('');setSaved(false);try{await apiRequest(`/api/staff/${id}/${path}`,{method,body:JSON.stringify(values)});setRevision(v=>v+1);setSaved(true);onChanged();return true;}catch(e){setError(e instanceof ApiError?[e.message,...Object.values(e.errors).flat()].join(' '):c.failed);return false;}finally{setBusy(false);}}
 async function attendance(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));if(await send('attendance',{...values,status,quantity:values.quantity||null,overtime_hours:values.overtime_hours||'0',overtime_rate:values.overtime_rate||'0'})){form.reset();setStatus('present');}}
 const previousMonth=new Date();previousMonth.setDate(1);previousMonth.setMonth(previousMonth.getMonth()-1);const through=dateInput(previousMonth).slice(0,7);
 return <div className="space-y-5">
 {error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{saved&&<p role="status" className="text-sm text-emerald-700">{c.saved}</p>}
 <section className="rounded-2xl border border-[var(--ac-line)] bg-white p-5"><h3 className="font-semibold">{c.title}</h3><p className="mt-2 text-xs leading-6 text-[var(--ac-text-muted)]">{c.help}</p>
 {canPay&&<form onSubmit={attendance}><fieldset disabled={busy} className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-xs">{c.date}<input required type="date" name="occurred_on" max={today()} defaultValue={today()} className={field}/></label><label className="text-xs">{c.title}<select className={field} value={status} onChange={e=>setStatus(e.target.value)}><option value="present">{c.present}</option><option value="absent">{c.absent}</option></select></label>
 {status==='present'&&<>{['hour','piece'].includes(basis)&&<label className="text-xs">{c.quantity} {basis==='piece'&&unit}<input required name="quantity" type="number" min="0.0001" max={basis==='hour'?24:9999} step="0.0001" className={field}/></label>}<label className="text-xs">{c.ot}<input name="overtime_hours" type="number" min="0" max="24" step="0.0001" defaultValue="0" className={field}/></label><label className="text-xs">{c.rate} ({currency})<input name="overtime_rate" type="number" min="0" max="999999" step="0.0001" defaultValue="0" className={field}/></label></>}
 <label className="text-xs">{c.notes}<input name="notes" maxLength={2000} className={field}/></label><button className="rounded-xl bg-[var(--ac-accent-strong)] p-3 text-sm text-white">{c.save}</button></fieldset></form>}
 <div className="mt-5 overflow-x-auto"><table className="w-full text-start text-xs"><thead className="bg-[var(--ac-surface-soft)]"><tr>{[c.date,c.title,c.quantity,c.ot].map((label,i)=><th key={i} className="p-3 text-start">{label}</th>)}</tr></thead><tbody>{data?.attendance.data.map(row=><tr key={row.id} className="border-b border-[var(--ac-line)]"><td className="p-3">{row.occurred_on}</td><td className="p-3">{row.status==='present'?c.present:c.absent}</td><td className="p-3">{row.quantity}</td><td className="p-3">{row.overtime_hours}</td></tr>)}</tbody></table>{data&&!data.attendance.data.length&&<p className="p-4 text-center text-xs">{c.empty}</p>}</div>
 {data&&data.attendance.last_page>1&&<div className="mt-3 flex justify-between"><button className={button} disabled={page===1} onClick={()=>setPage(p=>p-1)}>{c.previous}</button><button className={button} disabled={page===data.attendance.last_page} onClick={()=>setPage(p=>p+1)}>{c.next}</button></div>}</section>
 <details className="rounded-2xl border border-[var(--ac-line)] bg-white p-5"><summary className="cursor-pointer font-semibold">{c.rules}</summary><p className="mt-3 text-xs leading-6 text-[var(--ac-text-muted)]">{c.ruleHelp}</p>
 {canPay&&<form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));if(await send('adjustments',{...values,ends_on:values.ends_on||null}))form.reset();}}><fieldset disabled={busy} className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-xs">{c.label}<input required name="label" maxLength={255} className={field}/></label><label className="text-xs">{c.kind}<select name="kind" className={field}>{(['allowance','bonus','deduction'] as const).map(kind=><option key={kind} value={kind}>{c[kind]}</option>)}</select></label><label className="text-xs">{c.amount} ({currency})<input required name="amount" type="number" min="0.0001" max="999999999" step="0.0001" className={field}/></label><label className="text-xs">{c.start}<input required name="starts_on" type="date" defaultValue={today()} className={field}/></label><label className="text-xs">{c.end}<input name="ends_on" type="date" className={field}/></label><button className={button}>{c.add}</button></fieldset></form>}
 <div className="mt-5 space-y-2">{data?.adjustments.map(rule=><div key={rule.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-[var(--ac-surface-soft)] p-4"><div><strong className="text-sm">{rule.label}</strong><p className="mt-1 text-xs">{c[rule.kind as 'bonus'|'allowance'|'deduction']} · {rule.amount} {currency}</p><p className="mt-1 text-xs">{rule.starts_on} — {rule.ends_on??c.permanent}</p></div>{canPay&&(!rule.ends_on||rule.ends_on>today())&&rule.starts_on<=today()&&<button disabled={busy} className={button} onClick={()=>void send('adjustments/'+rule.id,{ends_on:today()},'PATCH')}>{c.stop}</button>}</div>)}</div>
 {canPay&&<form className="mt-4 flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();void send('adjustments/accrue',Object.fromEntries(new FormData(e.currentTarget)));}}><label className="text-xs">{c.through}<input required type="month" name="through" defaultValue={through} max={through} className={field}/></label><button disabled={busy} className={button}>{c.accrue}</button></form>}</details>
 </div>;
}
